plugins {
    alias(libs.plugins.android.application)
}

android {
    namespace 'com.example.ros2_controller'
    compileSdk {
        version = release(37)
    }

    defaultConfig {
        applicationId "com.example.ros2_controller"
        minSdk 26
        targetSdk 37
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

        // DDS Native C++/JNI 바이너리 아키텍처 설정
        ndk {
            abiFilters "arm64-v8a", "armeabi-v7a", "x86_64"
        }

    }

    buildTypes {
        release {
            optimization {
                enable false
            }
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
}

dependencies {
    implementation libs.activity.ktx
    implementation libs.appcompat
    implementation libs.constraintlayout
    implementation libs.material

    // ROS 2 Native DDS 라이브러리 (Fast-DDS)
    implementation 'us.ihmc:jros2-android:1.5.1'

    testImplementation libs.junit
    androidTestImplementation libs.espresso.core
    androidTestImplementation libs.ext.junit
}